name:                piggies-finance-tracker
version:             0.1.0.0
github:              "githubuser/piggies-finance-tracker"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/piggies-finance-tracker#readme>

dependencies:
- base >= 4.7 && < 5
- containers == 0.6.5.1
- QuickCheck == 2.14.2
- HUnit == 1.6.2.0
- hspec == 2.9.7
- text == 1.2.5.0
- aeson == 2.0.3.0
- bytestring == 0.11.3.1
- scientific == 0.3.7.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DeriveGeneric
- DerivingStrategies
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- ViewPatterns

library:
  source-dirs: src

executables:
  piggies-finance-tracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piggies-finance-tracker

tests:
  piggies-finance-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piggies-finance-tracker
